nodes:
  # Wazuh indexer node
  indexer:
    - name: wazuh-indexer
      ip: "172.26.0.11"

  # Wazuh server / manager node
  server:
    - name: wazuh-manager
      ip: "172.26.0.10"

  # Wazuh dashboard node
  dashboard:
    - name: wazuh-dashboard
      ip: "172.26.0.12"
